apiVersion: v1
kind: Service
metadata:
  name: product-svc
  namespace: shoppingportal
  labels:
    name: productsvc
spec:
  type: NodePort
  selector:
        name: product
        version: "1.0.0"
        release: stable
        tier: fe
        zone: prod
        managed-by: m2
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: my-http-port
